source 'http://rubygems.org'

gem "closure-compiler", "~> 1.1.1"
gem "rake"
gem "sprockets", "~> 1.0.2"
gem "compass"
gem "compass-rgbapng"

group :development do
  gem "capistrano", "~> 2.5.20"
  gem "capistrano-ext", "~> 1.2.1"
  gem "guard-shell", "~> 0.1.1"
  gem "guard-livereload", "~> 0.3.1"
  gem "foreman"
end
