require 'rake'
require 'rake/packagetask'
require 'yaml'
require 'sprockets'
require 'closure-compiler'

module KickassProjectHelper
  ROOT_DIR      = File.expand_path(File.dirname(__FILE__))
  SRC_DIR       = File.join(ROOT_DIR, 'src')
  DIST_DIR      = File.join(ROOT_DIR, '../public/js/ritverktyg')
  TEMPLATES_DIR = File.join(ROOT_DIR, 'templates')
  PKG_DIR       = File.join(ROOT_DIR, 'pkg')
  TEST_DIR      = File.join(ROOT_DIR, 'test')
  TEST_UNIT_DIR = File.join(TEST_DIR, 'unit')
  TMP_DIR       = File.join(TEST_UNIT_DIR, 'tmp')
  VERSION       = YAML.load(IO.read(File.join(SRC_DIR, 'constants.yml')))['PROJECT_VERSION']
  
  def self.compile(path, source, newName)
    closure = Closure::Compiler.new(:compilation_level => 'SIMPLE_OPTIMIZATIONS')
    compiledString = closure.compile(File.open(File.join(ROOT_DIR,path,source), 'r'))
    compiledFile = File.new(File.join(DIST_DIR, newName), "w")
    compiledFile.write(compiledString)
    compiledFile.close
    
  end
  def self.sprocketize(path, source, destination = nil, strip_comments = true)
    secretary = Sprockets::Secretary.new(
      :root           => File.join(ROOT_DIR, path),
      :load_path      => [SRC_DIR],
      :source_files   => [source],
      :strip_comments => strip_comments
    )
    
    destination = File.join(DIST_DIR, source) unless destination
    secretary.concatenation.save_to(destination)
  end
    
  def self.deploy_package(destination)
    cmd = ["/usr/bin/rsync", "-azp", "--delete", PKG_DIR+"/Project-"+VERSION+"/", destination].flatten.compact

    system(*cmd)
  end
    
end

%w[sprockets].each do |name|
  $:.unshift File.join(KickassProjectHelper::ROOT_DIR, 'vendor', name, 'lib')
end


task :default => [:dist]

desc "Builds the distribution."

task :clean_compile do
  KickassProjectHelper.sprocketize("src", "req.js")
  KickassProjectHelper.sprocketize("src", "build.js")
  KickassProjectHelper.compile("dist","build.js","compiled2.js")
end


task :compile do
  KickassProjectHelper.compile("dist","build.js","compiled.js")
end

task :dist do
  KickassProjectHelper.sprocketize("src", "req.js")
  KickassProjectHelper.sprocketize("src", "build.js")
end

task :deploy => [:dist, :package] do
  #KickassProjectHelper.deploy_package("martin@talkative.se:/var/spt/");
end

Rake::PackageTask.new('KickassProject', KickassProjectHelper::VERSION) do |package|
  package.need_tar_gz = true
  package.package_dir = KickassProjectHelper::PKG_DIR
  package.package_files.include(
    '[A-Z]*',
    'dist/build.js',
    'css/**',
    'img/**',    
    'index.html'
  )
end
